### ISSUE TITLE
USER STORY: Submit feedback via poll

### ISSUE THREAD

**Issue by Roybin0** [Roybin0/agile-project#1]
In order to **submit feedback** as an **experienced runner**, I can **quickly and easily complete the poll**.

### Acceptance Criteria: 

* Option to submit feedback anonymously and securely 
* Option to add a comment 
* Quick and simple use  

### Tasks 

- [ ] Create the poll with anonymity built in as a checkbox
- [ ] Set checkbox to be ticked by default and located beside **Submit** button 
- [ ] Include text box to submit comment 
- [ ] Update controller function
- [ ] Update test scripts 
- [ ] Test functionality
