### ISSUE TITLE
USER STORY: Add picture submission for real life experience 

### ISSUE THREAD

**Issue by Roybin0** [Roybin0/agile-project#3]
In order to **provide IRL feedback from experience** as a **user**, I can **upload pictures**.

### Acceptance Criteria: 

* File upload must be a certain format - .jpg. 
* Limit amount of pictures that can be uploaded 

### Tasks: 

- [ ] Add field for uploaded files to existing poll 
- [ ] Add functionality to check and restrict number of files added 
- [ ] Update test scripts
- [ ] Test functionality
