### ISSUE TITLE
USER STORY: Access and display historic poll data 

### ISSUE THREAD

**Issue by Roybin0** [Roybin0/agile-project#4]
### User Story

In order to **display previous vote results** as an **administrator**, I can **view historic poll results and easily display them on the website**.

### Acceptance Criteria: 

* Poll data is secure and easily accessible 
* Polls can be viewed by date
* Poll data can be displayed on the website 

### Tasks

- [ ] Update poll to include display of historic poll results on website via dropdown of poll titles 
- [ ] Create secure data storage so view and access historic data 
- [ ] Create date picker for administrator to view poll data
