### ISSUE TITLE
USER STORY: View historic poll results on website 

### ISSUE THREAD

**Issue by Roybin0** [Roybin0/agile-project#5]
### User Story 

In order to **view historic poll data** as a **user**, I can **see a selection of previous poll titles and select one to view the results**.

### Acceptance Criteria: 

* Poll data needs to be accurate and secure 
* Dropdown of previous poll titles 

### Tasks

- [ ] Update poll on website to include dropdown of historic poll titles 
- [ ] Create function to access and display historic data
- [ ] Update controller function
- [ ] Update test scripts 
- [ ] Test functionality
